### PR TITLE
Allow all list-like structures to be special forms

### PR DESCRIPTION
**Pull request by alexander-yakushev**
This includes LazySeq, Cons and maybe some others.

Easier to explain with code:
```clojure
(require '[hara.event :as ev])

(defn issue-fn []
  (ev/raise ::some-issue
            (option :use-value [v] v)))

(ev/manage (issue-fn)
           (on ::some-issue [] (ev/choose :use-value 42)))
;=> 42

(defmacro always-choose [form value]
  `(ev/manage ~form
              (~'on ::some-issue [] (ev/choose :use-value ~value))))

(always-choose (issue-fn) 42)
;; Unable to resolve symbol: on in this context

;;; But...

(defmacro always-choose2 [form value]
  `(ev/manage ~form
              ~(clojure.lang.PersistentList/create ;; WOW!
                `(~'on ::some-issue [] (ev/choose :use-value ~value)))))

(always-choose2 (issue-fn) 42)
;=> 42

(= (macroexpand-1 '(always-choose2 (issue-fn) 42))
   (macroexpand-1 '(always-choose2 (issue-fn) 42)))
;=> true

(= (macroexpand-1 (macroexpand-1 '(always-choose2 (issue-fn) 42)))
   (macroexpand-1 (macroexpand-1 '(always-choose2 (issue-fn) 42))))
;=> false
```

### CODE REVIEW

**Comment by zcaudate** [comment]
what happens with vectors? I used `list?` because I didn't want vectors to be included.

**Comment by alexander-yakushev** [comment]
Vector is not ISeq.

You can also change it to `(and (not vector? x) (sequential? x))`. But `list?` is usually a very weak predicate.

**Comment by zcaudate** [comment]
cool. I learnt something new today =)

**Comment by alexander-yakushev** [comment]
Thank you!

**Pull request merged**
